name: potatoes_secured_preferences
description: "A Preferences service with secure storage capabilities"
version: 1.0.2
homepage: https://www.caelis-tech.studio
repository: https://github.com/Venusdjinni/potatoes_secured_preferences
issue_tracker: https://github.com/Venusdjinni/potatoes_secured_preferences/issues
topics: [potatoes, shared-preferences, storage, secure]

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  potatoes: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
